name: "📖 User Story"
description: Document a feature from the user's perspective
title: "[STORY] "
labels: ["user-story", "needs-review"]
body:
  - type: markdown
    attributes:
      value: |
        ## User Story Template
        Document features from the user's perspective before decomposition into work orders.

  - type: input
    id: story_id
    attributes:
      label: Story ID
      description: Unique identifier (e.g., ADMIN-003, SCHED-001)
      placeholder: "ADMIN-003"
    validations:
      required: true

  - type: dropdown
    id: avatar
    attributes:
      label: User Avatar
      description: Who is this story for?
      options:
        - Administrator
        - Training Coordinator
        - Compliance Manager
        - Scheduler
        - DSP (Direct Support Professional)
        - Client/Family Member
    validations:
      required: true

  - type: textarea
    id: user_story
    attributes:
      label: User Story
      description: As a [avatar], I want [goal], so that [benefit]
      placeholder: |
        As an Administrator, I want the system to automatically start the correct onboarding process when a new employee is added, so that no new hire is missed.
    validations:
      required: true

  - type: textarea
    id: workflow
    attributes:
      label: Workflow Description
      description: Describe the step-by-step workflow
      placeholder: |
        1. User does X
        2. System responds with Y
        3. User confirms Z
    validations:
      required: true

  - type: textarea
    id: automations
    attributes:
      label: Automations & Triggers
      description: What automated processes are involved?
      placeholder: |
        **Trigger:** Event that starts the process
        **Automation:** What the system does automatically
        **Alert:** Notifications or activities created

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: How will we know this story is complete?
      placeholder: |
        **Backend:**
        - [ ] Criterion 1
        - [ ] Criterion 2
        
        **UI:**
        - [ ] Criterion 1
        
        **UAT:**
        - [ ] Criterion 1
    validations:
      required: true

  - type: dropdown
    id: system
    attributes:
      label: System
      options:
        - Hub
        - EVV
        - Both (Cross-System)
    validations:
      required: true

  - type: dropdown
    id: module_type
    attributes:
      label: Module Type
      options:
        - Core (All Tenants)
        - Add-on (Optional)
    validations:
      required: true

