name: BA - Epic to Story
on:
  issues:
    types: [opened, labeled]
permissions:
  contents: write
  pull-requests: write
  issues: write
jobs:
  ba_story:
    if: >-
      (github.event.action == 'labeled' && contains(github.event.label.name, 'type:epic'))
      ||
      (github.event.action == 'opened' && contains(toJson(github.event.issue.labels), 'type:epic'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
      - name: Run BA agent
        env:
          ROLE: ba
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/agent_runner.py

